---
# Playbook to control the mockfog_application role

- name: Rollout broker application
  hosts: broker_nodes # based on defined role
  remote_user: ec2-user
  become: yes
  roles:
    - mockfog_application_geobroker_server

- name: Rollout client application
  hosts: client_nodes
  remote_user: ec2-user
  become: yes
  roles:
    - mockfog_application_geobroker_client
